name: Twilight Toolkit Tests

on:
  push:
    branches:
      - main
    paths:
      - "packages/twilight-ui/**"
      - "packages/twilight-utils/**"
      - "package.json"
      - "bun.lock"
      - "turbo.json"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/twilight-ui/**"
      - "packages/twilight-utils/**"
      - "package.json"
      - "bun.lock"
      - "turbo.json"
      - ".github/workflows/**"

jobs:
  run-smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Twilight Utilities
        run: bun run build:twilight:utils

      - name: Build Twilight UI Storybook
        run: bun run build:twilight:ui:storybook
